export const ACTIONS = {
  SET_CONFIG: 'SET_CONFIG',
  SET_URL: 'SET_URL',
  SET_DIMENSIONS: 'SET_DIMENSIONS',
  SET_ATTRIBUTES: 'SET_ATTRIBUTES',
  SET_CUSTOM_ATTRIBUTES: 'SET_CUSTOM_ATTRIBUTES',
  SET_ERRORS: 'SET_ERRORS',
  SET_SELECTED_PRESET: 'SET_SELECTED_PRESET',
  SET_SELECTED_ATTRIBUTE_PRESET: 'SET_SELECTED_ATTRIBUTE_PRESET',
  SET_RENDER_MODE: 'SET_RENDER_MODE',
  SET_SHOW_EDIT_SETTINGS: 'SET_SHOW_EDIT_SETTINGS',
  SET_EXPAND_ALL_SECTIONS: 'SET_EXPAND_ALL_SECTIONS'
} as const; 